# Generated by Django 5.2.2 on 2025-06-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_alter_movie_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actor',
            field=models.ManyToManyField(related_name='actors', to='movie_app.actor'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.ManyToManyField(related_name='countries', to='movie_app.country'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ManyToManyField(related_name='directors', to='movie_app.director'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(related_name='genres', to='movie_app.genre'),
        ),
        migrations.AlterField(
            model_name='movielanguages',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='movie_videos/'),
        ),
    ]
